- change/@dlw-digitalworkplace-dw-react-controls-2021-06-25-14-32-36-task-cleanup-package.json
- change/@dlw-digitalworkplace-dw-react-utils-2021-06-25-14-32-36-task-cleanup-package.json
- packages/dw-react-controls/.storybook/main.js
- packages/dw-react-controls/.storybook/manager.js
- packages/dw-react-controls/package.json
- packages/dw-react-controls/src/components/TreeItem/TreeItem.test.tsx
- packages/dw-react-controls/src/components/TreeView/TreeView.test.tsx
- packages/dw-react-utils/package.json
- yarn.lock
> [Task] Cleanup packages

- change/@dlw-digitalworkplace-dw-react-controls-2021-06-25-17-04-28-master.json
- change/@dlw-digitalworkplace-dw-react-utils-2021-06-25-16-58-42-task-utils-package-version.json
- packages/dw-react-controls/package.json
- packages/dw-react-utils/package.json
Initializes utils package version
> [Task] Initialize utils package version

- change/@dlw-digitalworkplace-dw-react-controls-009ce899-58b7-4a23-acf6-d0ce0ea004c9.json
- packages/dw-react-controls/config/setupTests.js
- packages/dw-react-controls/package.json
- packages/dw-react-controls/src/components/TaxonomyPicker/TaxonomyPicker.base.tsx
- packages/dw-react-controls/src/components/TaxonomyPicker/TermAdder/TermAdder.base.tsx
- yarn.lock
Improve office ui fabric react import statements
> [Task] Improve import statements

- change/@dlw-digitalworkplace-taxonomyprovider-sharepoint-2021-07-02-16-58-26-bugfix-export-invalidoperationerror.json
- packages/taxonomyProviders/sharepoint/src/index.ts
> [Task] Export missing invalidoperationerror

- change/@dlw-digitalworkplace-dw-react-controls-8c4fefe0-c6a0-45e1-b558-8df122072a45.json
- change/@dlw-digitalworkplace-dw-refresh-cache-3dcc9bb1-0786-4ec7-823c-63d7a8fe0946.json
- packages/dw-react-controls/src/components/TreeView/index.ts
- packages/dw-refresh-cache/src/index.ts
Fix default exports not being exposed in root.
> [Bugfix] Fix default exports

- .storybook/preview-head.html
- .storybook/previewUtils.js
- change/@dlw-digitalworkplace-dw-refresh-cache-c54fdb72-03d9-4cf8-b72e-fe97ba2d9b88.json
- change/@dlw-digitalworkplace-taxonomyprovider-sharepoint-f5fe1ab0-ec42-462e-9736-ac727aee1745.json
- packages/dw-refresh-cache/src/stories/RefreshCache.stories.mdx
- packages/taxonomyProviders/sharepoint/src/stories/SharePointTaxonomyProvider.stories.mdx
- yarn.lock
Added documentation for missing packages
> [Docs] Add missing package documentation

- apps/demo-spfx-app/package.json
- change/@dlw-digitalworkplace-dw-react-controls-5da3eee4-abca-435a-a625-a0c3bebff7aa.json
- change/@dlw-digitalworkplace-dw-react-utils-c5a8a803-3f8e-447e-af2e-e6e6a2b0bb36.json
- change/@dlw-digitalworkplace-dw-refresh-cache-e9af2c76-cab9-426f-a90b-ca0c36fd9501.json
- change/@dlw-digitalworkplace-taxonomyprovider-sharepoint-eb03a32d-0152-4662-8988-db7fb9d49324.json
- packages/dw-react-controls/package.json
- packages/dw-react-utils/package.json
- packages/dw-refresh-cache/package.json
- packages/taxonomyProviders/sharepoint/package.json
- yarn.lock
Add tslib to package dependencies
> [Bugfix] Add tslib to package dependencies

- .storybook/previewUtils.js
- change/@dlw-digitalworkplace-dw-refresh-cache-5c8ca66c-3897-4e4d-8caa-5b506555ffb8.json
- packages/dw-refresh-cache/src/stories/MemoryStorage.stories.mdx
Add MemoryStorage documentation
> [Docs] Add MemoryStorage documentation

- change/@dlw-digitalworkplace-dw-react-controls-4b845857-9989-400b-ae35-3df13399f5a9.json
- packages/dw-react-controls/src/components/TaxonomyPicker/TaxonomyPicker.base.tsx
- packages/dw-react-controls/src/components/TaxonomyPicker/TaxonomyPicker.stories.mdx
- packages/dw-react-controls/src/components/TaxonomyPicker/TaxonomyPicker.styles.ts
- packages/dw-react-controls/src/components/TaxonomyPicker/TaxonomyPicker.types.ts
- packages/dw-react-controls/src/components/TermPicker/TermPicker.styles.ts
- packages/dw-react-controls/src/components/TermPicker/TermPicker.tsx
- packages/dw-react-controls/src/components/TermPicker/TermPicker.types.ts
- packages/dw-react-controls/src/index.ts
- packages/dw-react-controls/src/utilities/index.ts
- packages/dw-react-controls/src/utilities/useTheme.ts
Added better custom styling support.
Style picker as invalid when too many items are selected.
> [TaxonomyPicker] Show invalid state when too many items selected, better custom styling support

- change/@dlw-digitalworkplace-dw-react-utils-ca8525fc-37da-40a2-9082-b713159950ad.json
- change/@dlw-digitalworkplace-dw-refresh-cache-15143e16-5e44-4b3f-9ec5-23f43f5d2660.json
- change/@dlw-digitalworkplace-taxonomyprovider-sharepoint-4d8a1542-120a-4a1c-8e59-498cd09a7d53.json
- packages/dw-react-utils/src/stories/hooks/useControlled.stories.mdx
- packages/dw-react-utils/src/stories/hooks/useIsMounted.stories.mdx
- packages/dw-react-utils/src/stories/hooks/useStateIfMounted.stories.mdx
- packages/dw-react-utils/src/stories/utils/collections/findInTree.stories.mdx
- packages/dw-react-utils/src/stories/utils/collections/flatten.stories.mdx
- packages/dw-react-utils/src/stories/utils/escapeRegExp.stories.mdx
- packages/dw-refresh-cache/src/stories/MemoryStorage.stories.mdx
- packages/dw-refresh-cache/src/stories/RefreshCache.stories.mdx
- packages/taxonomyProviders/sharepoint/src/stories/SharePointTaxonomyProvider.stories.mdx
- stories/Introduction.stories.mdx
Docs update for utils & missing imports
> [Docs] Docs update

- package.json
Fix compilation issue due to @uifabric nohoist
> [Docs] Fix docs compilation

- change/@dlw-digitalworkplace-dw-spfx-controls-4813ce24-3bec-4303-9715-014d64bf44c5.json
- packages/dw-spfx-controls/CHANGELOG.json
- packages/dw-spfx-controls/CHANGELOG.md
- packages/dw-spfx-controls/src/components/WebPartTitle/WebPartTitle.styles.ts
Fix issue with more info link margin.
> [WebPartTitle] Fix issue with more info link margin

- change/@dlw-digitalworkplace-dw-react-controls-4c7ea147-f3d7-402b-974d-4cb0d01748ea.json
- change/@dlw-digitalworkplace-taxonomyprovider-sharepoint-a13d8fec-10d0-4cbd-aded-89603de45efd.json
- packages/dw-react-controls/src/components/TermPicker/TermPicker.tsx
- packages/taxonomyProviders/sharepoint/package.json
Fixes an issue with TermPicker showing currently selected items as suggestions in a callout.
> fix(termpicker): Fix issue with picker showing current items as suggestions

- .github/issue_template.md
Added a issue_template.md file to the repo which will make it easier for people to create issues
> Feature: Add issue template

- change/@dlw-digitalworkplace-dw-refresh-cache-1be84548-ecce-4bf4-88f8-8e825016f97d.json
- packages/dw-refresh-cache/src/RefreshCache.ts
- packages/dw-refresh-cache/src/stories/RefreshCache.stories.mdx
- packages/dw-refresh-cache/src/tests/RefreshCache.test.ts
BREAKING: change TTL to receive seconds instead of ms
ref: #46
> feat: change TTL to receive seconds instead of ms

- apps/demo-spfx-app/package.json
- apps/demo-spfx-app/src/webparts/demoPeoplePicker/DemoPeoplePickerWebPart.tsx
- apps/demo-spfx-app/src/webparts/demoPeoplePicker/DemoPeoplePickerWebPart.types.ts
- change/@dlw-digitalworkplace-dw-react-controls-4afd5e43-51ff-4bf2-a180-fba44afaf122.json
- change/@dlw-digitalworkplace-peoplepickerprovider-graph-6dbb49b0-a06c-461c-99e7-9530a41c6161.json
- change/@dlw-digitalworkplace-peoplepickerprovider-sharepoint-fa1107c8-78cf-4bc3-9488-f01df11e5f64.json
- packages/dw-react-controls/src/components/PeoplePicker/PeoplePicker.base.tsx
- packages/dw-react-controls/src/components/PeoplePicker/models/IPeoplePickerProvider.ts
- packages/dw-react-controls/src/components/PeoplePicker/providers/MockPeoplePickerProvider.ts
- packages/dw-react-controls/src/components/PeoplePicker/stories/PeoplePicker.stories.mdx
- packages/dw-react-controls/src/components/PeoplePicker/stories/PeoplePicker.stories.tsx
- packages/dw-react-controls/stories/Introduction.stories.mdx
- packages/peoplePickerProviders/graph/src/GraphPeoplePickerProvider.ts
- packages/peoplePickerProviders/graph/src/stories/GraphPeoplePickerProvider.stories.mdx
- packages/peoplePickerProviders/graph/src/tests/GraphPeoplePickerProvider.test.ts
- packages/peoplePickerProviders/sharepoint/.npmignore
- packages/peoplePickerProviders/sharepoint/CHANGELOG.json
- packages/peoplePickerProviders/sharepoint/CHANGELOG.md
- packages/peoplePickerProviders/sharepoint/config/setupTests.js
- packages/peoplePickerProviders/sharepoint/just.config.ts
- packages/peoplePickerProviders/sharepoint/package.json
- packages/peoplePickerProviders/sharepoint/src/SharePointPeoplePickerProvider.ts
- packages/peoplePickerProviders/sharepoint/src/index.ts
- packages/peoplePickerProviders/sharepoint/src/models/ISharePointPeoplePickerProviderOptions.ts
- packages/peoplePickerProviders/sharepoint/src/models/PrincipalType.ts
- packages/peoplePickerProviders/sharepoint/src/stories/SharePointPeoplePickerProvider.stories.mdx
- packages/peoplePickerProviders/sharepoint/stories/Changelog.stories.mdx
- packages/peoplePickerProviders/sharepoint/tsconfig.json
- packages/peoplePickerProviders/sharepoint/tslint.json
- stories/Introduction.stories.mdx
> feat: sharepoint peoplepickerprovider

- change/@dlw-digitalworkplace-peoplepickerprovider-graph-e9685818-b458-4ca7-ba08-e41e2b62b0e9.json
- packages/peoplePickerProviders/graph/src/GraphPeoplePickerProvider.ts
Filter users only by valid guids
> fix(peoplepicker-graph): filter users only by valid guids

- .github/workflows/pr.yml
- .github/workflows/release-canary.yml
- .github/workflows/release.yml
- change/@dlw-digitalworkplace-dw-react-controls-139d0133-c54f-4faf-848f-98d0b7d75dfc.json
- change/@dlw-digitalworkplace-dw-react-utils-2aaa7561-ea16-40cf-a58d-754fa4426207.json
- change/@dlw-digitalworkplace-dw-refresh-cache-76b704fa-e893-4f3f-b5f0-5963fb4be967.json
- change/@dlw-digitalworkplace-peoplepickerprovider-graph-ebad01d1-1f51-4620-81d8-dbc80220f940.json
- change/@dlw-digitalworkplace-peoplepickerprovider-sharepoint-94953125-b00b-4cfe-bd6a-1c21149a57fd.json
- change/@dlw-digitalworkplace-taxonomyprovider-sharepoint-dae45db8-44df-4fd4-bcfe-81de34faba81.json
- packages/dw-react-controls/.npmignore
- packages/dw-react-controls/src/components/TreeView/TreeView.base.tsx
- packages/dw-react-utils/.npmignore
- packages/dw-refresh-cache/.npmignore
- packages/peoplePickerProviders/graph/.npmignore
- packages/peoplePickerProviders/sharepoint/.npmignore
- packages/taxonomyProviders/sharepoint/.npmignore
- scripts/just.config.ts
focus first node when focusing treeview
> fix(treeview): focus first node when focusing treeview

- .github/workflows/release-canary.yml
- .github/workflows/release.yml
Fix sourcemap format for builds
> fix: sourcemap format for builds

- .github/workflows/release-canary.yml
- .github/workflows/release.yml
- change/@dlw-digitalworkplace-dw-react-controls-manual.json
- change/@dlw-digitalworkplace-dw-react-utils-manual.json
- change/@dlw-digitalworkplace-dw-refresh-cache-manual.json
- change/@dlw-digitalworkplace-dw-spfx-controls-manual.json
- change/@dlw-digitalworkplace-peoplepickerprovider-graph-manual.json
- change/@dlw-digitalworkplace-peoplepickerprovider-sharepoint.json
- change/@dlw-digitalworkplace-taxonomyprovider-sharepoint.json
- package.json
- packages/dw-react-controls/.npmignore
- packages/dw-react-utils/.npmignore
- packages/dw-refresh-cache/.npmignore
- packages/peoplePickerProviders/graph/.npmignore
- packages/peoplePickerProviders/sharepoint/.npmignore
- packages/taxonomyProviders/sharepoint/.npmignore
> fix: release production build

- change/@dlw-digitalworkplace-dw-react-utils-c79f8f6f-76fb-4f0a-ac12-d648d83fb35d.json
- packages/dw-react-utils/src/hooks/index.ts
- packages/dw-react-utils/src/hooks/useAutoRefresh.ts
- packages/dw-react-utils/src/stories/hooks/useAutoRefresh.stories.mdx
- packages/dw-react-utils/src/stories/hooks/useAutoRefresh.stories.tsx
- packages/dw-react-utils/src/tests/hooks/useAutoRefresh.test.ts
Adds a `useAutoRefresh` hook.
(PS: thanks ChatGPT for the unit tests 😄🖥️)
> feat: useAutoRefresh hook

- apps/demo-spfx-app/package.json
- apps/demo-spfx-app/tsconfig.json
- change/@dlw-digitalworkplace-dw-react-controls-3e142cf1-b32e-4c79-9296-ed6113a5bf04.json
- packages/dw-react-controls/package.json
- packages/dw-react-controls/src/components/PeoplePicker/PeoplePicker.types.ts
- yarn.lock
Add support for React v18 for the react-controls package
> feat: React v18 support for react-controls
